# Generated by Django 4.2.7 on 2023-11-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_name_jobs_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='username',
        ),
    ]
