# Generated by Django 4.2.7 on 2023-11-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobs_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
