# Generated by Django 4.2.7 on 2023-11-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
