# Generated by Django 4.2.7 on 2023-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_jobs_cost_alter_jobs_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_record', models.CharField(max_length=30)),
                ('total_jobs', models.CharField(max_length=20)),
                ('total_sav', models.CharField(blank=True, max_length=20, null=True)),
                ('total_flex', models.CharField(blank=True, max_length=20, null=True)),
                ('total_cost', models.CharField(blank=True, max_length=20, null=True)),
                ('close_account', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
